### PR TITLE
chore: translate partially what is webpack [WIP]

### PR DESCRIPTION
**Pull request by juanpicado**
The idea is to translate the whole file 👍

### CODE REVIEW

**Comment by bebraw** [comment]
@shadowz10 Can you review and merge? My Spanish isn't too great. 👍

**Comment by juanpicado** [comment]
@shadowz10 give me some days to finish first the whole content and also I want to be agreed how some terms should be translated. eg: Whether makes sense to translate specific webpack keywords as "output" or "import". We know in Spanish we are get used in IT world to use English terms over the translated ones (which the most of the time it sounds terrible)

**Comment by TiburonzinGT** [comment]
@juanpicado Okay, @bebraw added a few changes today, are not they? and thanks for the suggestions I'll take them into account

**Comment by juanpicado** [comment]
@shadowz10 actually was mostly a question that an affirmation :) . I'll finish the document translation then.

**Comment by marioterron** [comment]
I completely agree with @juanpicado, there are some terms that don't make sense to translate into spanish as we usually refer to them in english.

**Pull request closed without merging**
